# Generated by Django 5.1.1 on 2026-07-27 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('09:00 - 10:00 AM', '09:00 - 10:00 AM'), ('10:00 - 11:00 AM', '10:00 - 11:00 AM'), ('11:00 AM - 12:00 PM', '11:00 AM - 12:00 PM'), ('02:00 - 03:00 PM', '02:00 - 03:00 PM'), ('03:00 - 04:00 PM', '03:00 - 04:00 PM'), ('04:00 - 05:00 PM', '04:00 - 05:00 PM')], max_length=50)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('checked-in', 'Checked In'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('no_sql_data', models.JSONField(blank=True, default=dict, help_text='Vitals, dynamic health data, checklist parameters')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('staff', 'Staff')], default='patient', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('specialty', models.CharField(blank=True, help_text='For doctors only', max_length=100, null=True)),
                ('no_sql_data', models.JSONField(blank=True, default=dict, help_text='Flexible dynamic metadata (NoSQL-like)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
